---
models:
  ZTE_ZXHN_H298A:
    - 'ZTE ZXHN H298A V1.1, firmware: V1.1.20_ROST16'
    - ZTE_ZXHN_H298A
    - ZTE ZXHN H298A V1.1
    - ZTE ZXHN H298A V1.1, firmware
  ZTE_F612:
    - ZTE_F612
    - ZTE ZXHN H118N
  ZTE_F670:
    - ZTE_F670
  Airocon:
    - 'Airocon UR-344AN4G, firmware: V2.1.4'
    - 'Airocon UR-344AN4G, firmware: V2.1.3'
    - 'Airocon F@st 1744,v2, firmware'
    - Airocon F@st 1744, v2, firmware
    - Airocon
  SERCOMM_RV6699:
    - SERCOMM RV6699
routers:
  ZTE_ZXHN_H298A:
    login:
      username:
        type: id
        location: Frm_Username
      password:
        type: id
        location: Frm_Password
      submit:
        type: id
        location: LoginId
    steps:
    - type: id
      location: LANUrl
    - type: id
      location: smDns
    - type: id
      location: LocalDnsServerBar
    dns:
      split_octets: true
      dns_1:
        type: id
        location:
        - sub_SerIPAddress10
        - sub_SerIPAddress11
        - sub_SerIPAddress12
        - sub_SerIPAddress13
      dns_2:
        type: id
        location:
        - sub_SerIPAddress20
        - sub_SerIPAddress21
        - sub_SerIPAddress22
        - sub_SerIPAddress23
      submit:
        type: id
        location: Btn_apply_LocalDnsServer
  ZTE_F612:
    login:
      username:
        type: id
        location: Frm_Username
      password:
        type: id
        location: Frm_Password
      submit:
        type: id
        location: LoginId
#      check_login:
#        type: xpath
#        location: //*[contains(text(),'Logout')]
    iframe: mainFrame
    steps:
    - type: id
      location: mmNet
    - type: xpath
      location: '/html/body/div[3]/div[1]/div[1]/table/tbody/tr/td/table/tbody/tr[9]'
    - type: xpath
      location: '/html/body/div[3]/div[1]/div[1]/table/tbody/tr/td/table/tbody/tr[6]'
    dns:
      split_octets: false
      dns_1:
        type: id
        location: Frm_DNSServer1
      dns_2:
        type: id
        location: Frm_DNSServer2
      submit:
        type: id
        location: Btn_Submit
  ZTE_F670:
    login:
      username:
        type: id
        location: Frm_Username
      password:
        type: id
        location: Frm_Password
      submit:
        type: id
        location: LoginId
#      check_login:
#        iframe: mainFrame
#        type: xpath
#        location: //*[contains(text(),'Logout')]
    iframe: mainFrame
    steps:
    - type: id
      location: mmNet
    - type: xpath
      location: '/html/body/div[3]/div[1]/div[1]/table/tbody/tr/td/table/tbody/tr[13]'
    dns:
      split_octets: false
      dns_1:
        type: id
        location: Frm_DNSServer1
      dns_2:
        type: id
        location: Frm_DNSServer2
      submit:
        type: id
        location: Btn_Submit
  Airocon:
    login:
      username:
        type: id
        location: username
      password:
        type: id
        location: password
      submit:
        type: id
        location: loginBtn
    steps:
    - type: xpath
      location: '/html/body/div/div[1]/div[2]/ul/li[3]/a'
    - type: xpath
      location: '//*[@id="side"]/li[2]/h3/a'
    - type: xpath
      location: '/html/body/div/div[2]/div[1]/div[1]/div/ul/li[2]/ul/li[2]/a'
    dns:
      iframe: contentIframe
      split_octets: false
      check_dhcp_mode:
        type: xpath
        location: '/html/body/form/div[3]/table/tbody/tr[7]/td/select'
      update_dhcp_mode:
        type: xpath
        location: '/html/body/form/div[3]/table/tbody/tr[7]/td/select'
        value: 1
      dns_1:
        type: xpath
        location: '//*[@id="manual_dns1"]/td/input'
      dns_2:
        type: xpath
        location: '//*[@id="manual_dns2"]/td/input'
      submit:
        type: xpath
        location: '/html/body/form/div[5]/div/input[1]'
  SERCOMM_RV6699:
    login:
      basic: true
    steps:
    - type: id
      location: Menu1Txt1
    dns:
      split_octets: true
      dns_1:
        type: xpath
        location:
        - '//*[@id="id_dns_servers_1"]/td[2]/input[1]'
        - '//*[@id="id_dns_servers_1"]/td[2]/input[2]'
        - '//*[@id="id_dns_servers_1"]/td[2]/input[3]'
        - '//*[@id="id_dns_servers_1"]/td[2]/input[4]'
      dns_2:
        type: xpath
        location:
        - '//*[@id="id_dns_servers_2"]/td[2]/input[1]'
        - '//*[@id="id_dns_servers_2"]/td[2]/input[2]'
        - '//*[@id="id_dns_servers_2"]/td[2]/input[3]'
        - '//*[@id="id_dns_servers_2"]/td[2]/input[4]'
      submit:
        type: xpath
        location: '/html/body/table/tbody/tr/td[3]/table/tbody/tr[3]/td/table/tbody/tr/td/form/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[8]/td/p/input[1]'
